# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: 名称:编号.js包

on:
  release:
    types: [    类型:[创建]]

jobs:
  build:
    runs-on:     最新运行:
    steps:
      - uses:       - uses: actions/checkout@v4
      - uses:       - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run:       - run: npm ci
      - run:       -运行:国家预防机制测试

  publish-gpr:
    needs:     需求:建设
    runs-on:     最新运行:
    permissions:
      contents:       内容:改为
      packages:       包装:书写
    steps:
      - uses:       - uses: actions/checkout@v4
      - uses:       - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url:           registry-url: https://npm.pkg.github.com/://npm.pkg.github.com/
      - run:       - run: npm ci
      - run:       -运行:国家预防机制公布
        环境 :
          荷兰语 :$ { {          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}} }
